### PR TITLE
Update whitespace.txt

### PR DESCRIPTION
**Pull request by ravimist-test**

### CODE REVIEW

**Comment by ravimist-test** [comment]
@googlebot I signed it!

**Comment by rmistry** [comment]
This PR (HEAD: dd59874c205b44f7a8cf3d732cba4003a2f002a0) has been imported to Gerrit for code review.

				Please visit https://skia-review.googlesource.com/c/buildbot/+/335076 to see it.

				Note:
				* Skia uses only Gerrit for reviews and submitting code ([doc](https://skia.org/dev/contrib)).
				* All comments are handled within Gerrit. Any comments on the Github PR will be ignored.
				* The PR author can continue to upload commits to the branch used by the PR in order to address feedback from Gerrit.
				* Once the code is ready to be merged, a maintainer will submit the change on Gerrit and skia-codereview-bot will close the issue.
				* Similarly, if a change is closed or abandoned on Gerrit, the corresponding PR will be closed.

**Comment by rmistry** [comment]
This PR (HEAD: dd59874c205b44f7a8cf3d732cba4003a2f002a0) has been imported to Gerrit for code review.

Please visit https://skia-review.googlesource.com/c/buildbot/+/335076 to see it.

Note:
* Skia uses only Gerrit for reviews and submitting code ([doc](https://skia.org/dev/contrib)).
* All comments are handled within Gerrit. Any comments on the Github PR will be ignored.
* The PR author can continue to upload commits to the branch used by the PR in order to address feedback from Gerrit.
* Once the code is ready to be merged, a maintainer will submit the change on Gerrit and skia-codereview-bot will close the issue.
* Similarly, if a change is closed or abandoned on Gerrit, the corresponding PR will be closed.

**Comment by rmistry** [comment]
This PR (HEAD: dd59874c205b44f7a8cf3d732cba4003a2f002a0) has been imported to Gerrit for code review.

Please visit https://skia-review.googlesource.com/c/buildbot/+/335076 to see it.

Note:
* Skia uses only Gerrit for reviews and submitting code ([doc](https://skia.org/dev/contrib)).
* All comments are handled within Gerrit. Any comments on the GitHub PR will be ignored.
* The PR author can continue to upload commits to the branch used by the PR in order to address feedback from Gerrit.
* Once the code is ready to be merged, a maintainer will submit the change on Gerrit and skia-codereview-bot will close this PR.
* Similarly, if a change is abandoned on Gerrit, the corresponding PR will be closed with the note used to abandon.

**Comment by rmistry** [comment]
This PR is being closed because [review.skia.org/335076](https://skia-review.googlesource.com/c/buildbot/+/335076) has been abandoned.

Was testing

**Pull request closed without merging**
