### PR TITLE
Code smell + micro performance tweak

### PR DESCRIPTION
**Pull request by eavichay**

### CODE REVIEW

**Comment by eavichay** [comment]
I Signed.

**Comment by kjlubick** [comment]
Thanks for the patch!  I realized we don't have tests yet for dom.js, so I'll add those and then pull in your change, making sure you get credit in the Author: field.

**Comment by kjlubick** [comment]
It was merged in https://skia-review.googlesource.com/c/buildbot/+/137386

There is no way to directly take a Github pull request and put it into our source code, since we are hosted on googlesource.com by default.

Next time, if you would be so kind as to use depot_tools and `git cl upload` to upload it, we'll be able to maintain the author info and review/test it better.  See https://skia.org/dev/contrib/submit for more details.

Thanks again!

**Comment by jcgregorio** [comment]
Landed here: https://skia-review.googlesource.com/c/buildbot/+/137386  
Thanks!

**Pull request closed without merging**
